# .github/workflows/ci-windows.yml
name: C++ CI/CD with Qt (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install Qt 6
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.6.2"
          host: windows

      # # 3. Install build tools (MSVC)
      # - name: Setup MSVC
      #   uses: actions/setup-msbuild@v1

      # 4. Configure CMake
      - name: Configure CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      # 5. Build all targets (GUI + tests)
      - name: Build project
        run: cmake --build build --config Release --parallel

      # 6. Run tests
      - name: Run tests
        run: ctest --test-dir build

      # # 7. List build folder
      # - name: List build folder
      #   run: dir build /s

      # 8. Package executable
      - name: Package executable
        run: |
          mkdir release
          copy build\Release\appTicTacToe.exe release\
          cd release
          powershell Compress-Archive -Path appTicTacToe.exe -DestinationPath appTicTacToe.zip

      # 9. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-executable
          path: release\appTicTacToe.zip
