name: C++ CI/CD with Qt

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Qt 6
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: "6.6.2"
          host: linux

      # Install build tools
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make zip

      # Configure CMake
      - name: Configure CMake
        run: cmake -S . -B build

      # Build all targets
      - name: Build project
        run: cmake --build build --parallel

      # Run tests
      - name: Run tests
        run: ctest --test-dir build

      # Package the executable
      - name: Package executable
        run: |
          mkdir -p release
          cp build/appTicTacToe release/
          cd release
          zip -r appTicTacToe .zip appTicTacToe

      # Upload as workflow artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-executable
          path: release/appTicTacToe.zip
